In [90]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

In [91]:
df = pd.read_csv("car_data.csv")
print(df.head())

  Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0  


In [92]:
df.drop(["Year" , "Owner" , "Present_Price"] , axis = 1 , inplace = True)
print(df.head())

  Car_Name  Selling_Price  Kms_Driven Fuel_Type Seller_Type Transmission
0     ritz           3.35       27000    Petrol      Dealer       Manual
1      sx4           4.75       43000    Diesel      Dealer       Manual
2     ciaz           7.25        6900    Petrol      Dealer       Manual
3  wagon r           2.85        5200    Petrol      Dealer       Manual
4    swift           4.60       42450    Diesel      Dealer       Manual


In [93]:
pd.set_option('display.max_rows', None)
df['Car_Name'].value_counts()

Car_Name
city                         26
corolla altis                16
verna                        14
fortuner                     11
brio                         10
ciaz                          9
innova                        9
i20                           9
grand i10                     8
Royal Enfield Classic 350     7
amaze                         7
jazz                          7
sx4                           6
ertiga                        6
eon                           6
swift                         5
alto k10                      5
i10                           5
ritz                          4
wagon r                       4
dzire                         4
etios liva                    4
Royal Enfield Thunder 350     4
Bajaj Pulsar 150              4
etios cross                   3
etios g                       3
Royal Enfield Thunder 500     3
Bajaj Avenger 220             3
Honda CB Hornet 160R          3
Yamaha FZ S V 2.0             3
TVS Apache RTR 160            3

In [94]:
pd.set_option('display.max_rows', None)
df['Seller_Type'].value_counts()

Seller_Type
Dealer        195
Individual    106
Name: count, dtype: int64

One hot encoding using pandas

In [95]:
pd.get_dummies(df,columns = ['Car_Name','Seller_Type'],dtype = int)

,Selling_Price,Kms_Driven,Fuel_Type,Transmission,Car_Name_800,Car_Name_Activa 3g,Car_Name_Activa 4g,Car_Name_Bajaj ct 100,Car_Name_Bajaj Avenger 150,Car_Name_Bajaj Avenger 150 street,Car_Name_Bajaj Avenger 220,Car_Name_Bajaj Avenger 220 dtsi,Car_Name_Bajaj Avenger Street 220,Car_Name_Bajaj Discover 100,Car_Name_Bajaj Discover 125,Car_Name_Bajaj Dominar 400,Car_Name_Bajaj Pulsar NS 200,Car_Name_Bajaj Pulsar 135 LS,Car_Name_Bajaj Pulsar 150,Car_Name_Bajaj Pulsar 220 F,Car_Name_Bajaj Pulsar NS 200,Car_Name_Bajaj Pulsar RS200,Car_Name_Hero CBZ Xtreme,Car_Name_Hero Ignitor Disc,Car_Name_Hero Extreme,Car_Name_Hero Glamour,Car_Name_Hero Honda CBZ extreme,Car_Name_Hero Honda Passion Pro,Car_Name_Hero Hunk,Car_Name_Hero Passion Pro,Car_Name_Hero Passion X pro,Car_Name_Hero Splender Plus,Car_Name_Hero Splender iSmart,Car_Name_Hero Super Splendor,Car_Name_Honda Activa 125,Car_Name_Honda Activa 4G,Car_Name_Honda CB Hornet 160R,Car_Name_Honda CB Shine,Car_Name_Honda CB Trigger,Car_Name_Honda CB Unicorn,Car_Name_Honda CB twister,Car_Name_Honda CBR 150,Car_Name_Honda Dream Yuga,Car_Name_Honda Karizma,Car_Name_Hyosung GT250R,Car_Name_KTM 390 Duke,Car_Name_KTM RC200,Car_Name_KTM RC390,Car_Name_Mahindra Mojo XT300,Car_Name_Royal Enfield Bullet 350,Car_Name_Royal Enfield Classic 350,Car_Name_Royal Enfield Classic 500,Car_Name_Royal Enfield Thunder 350,Car_Name_Royal Enfield Thunder 500,Car_Name_Suzuki Access 125,Car_Name_TVS Apache RTR 160,Car_Name_TVS Apache RTR 180,Car_Name_TVS Jupyter,Car_Name_TVS Sport,Car_Name_TVS Wego,Car_Name_UM Renegade Mojave,Car_Name_Yamaha FZ v 2.0,Car_Name_Yamaha FZ 16,Car_Name_Yamaha FZ S,Car_Name_Yamaha FZ S V 2.0,Car_Name_Yamaha Fazer,Car_Name_alto 800,Car_Name_alto k10,Car_Name_amaze,Car_Name_baleno,Car_Name_brio,Car_Name_camry,Car_Name_ciaz,Car_Name_city,Car_Name_corolla,Car_Name_corolla altis,Car_Name_creta,Car_Name_dzire,Car_Name_elantra,Car_Name_eon,Car_Name_ertiga,Car_Name_etios cross,Car_Name_etios g,Car_Name_etios gd,Car_Name_etios liva,Car_Name_fortuner,Car_Name_grand i10,Car_Name_i10,Car_Name_i20,Car_Name_ignis,Car_Name_innova,Car_Name_jazz,Car_Name_land cruiser,Car_Name_omni,Car_Name_ritz,Car_Name_s cross,Car_Name_swift,Car_Name_sx4,Car_Name_verna,Car_Name_vitara brezza,Car_Name_wagon r,Car_Name_xcent,Seller_Type_Dealer,Seller_Type_Individual
0,3.35,27000,Petrol,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0
1,4.75,43000,Diesel,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
2,7.25,6900,Petrol,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,2.85,5200,Petrol,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0
4,4.60,42450,Diesel,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
5,9.25,2071,Diesel,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0
6,6.75,18796,Petrol,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
7,6.50,33429,Diesel,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,

optimizing one hot encoding doen by pamda by removing extra collumns

In [96]:
pd.get_dummies(df,columns = ['Car_Name','Seller_Type'],dtype = int,drop_first = True)

,Selling_Price,Kms_Driven,Fuel_Type,Transmission,Car_Name_Activa 3g,Car_Name_Activa 4g,Car_Name_Bajaj ct 100,Car_Name_Bajaj Avenger 150,Car_Name_Bajaj Avenger 150 street,Car_Name_Bajaj Avenger 220,Car_Name_Bajaj Avenger 220 dtsi,Car_Name_Bajaj Avenger Street 220,Car_Name_Bajaj Discover 100,Car_Name_Bajaj Discover 125,Car_Name_Bajaj Dominar 400,Car_Name_Bajaj Pulsar NS 200,Car_Name_Bajaj Pulsar 135 LS,Car_Name_Bajaj Pulsar 150,Car_Name_Bajaj Pulsar 220 F,Car_Name_Bajaj Pulsar NS 200,Car_Name_Bajaj Pulsar RS200,Car_Name_Hero CBZ Xtreme,Car_Name_Hero Ignitor Disc,Car_Name_Hero Extreme,Car_Name_Hero Glamour,Car_Name_Hero Honda CBZ extreme,Car_Name_Hero Honda Passion Pro,Car_Name_Hero Hunk,Car_Name_Hero Passion Pro,Car_Name_Hero Passion X pro,Car_Name_Hero Splender Plus,Car_Name_Hero Splender iSmart,Car_Name_Hero Super Splendor,Car_Name_Honda Activa 125,Car_Name_Honda Activa 4G,Car_Name_Honda CB Hornet 160R,Car_Name_Honda CB Shine,Car_Name_Honda CB Trigger,Car_Name_Honda CB Unicorn,Car_Name_Honda CB twister,Car_Name_Honda CBR 150,Car_Name_Honda Dream Yuga,Car_Name_Honda Karizma,Car_Name_Hyosung GT250R,Car_Name_KTM 390 Duke,Car_Name_KTM RC200,Car_Name_KTM RC390,Car_Name_Mahindra Mojo XT300,Car_Name_Royal Enfield Bullet 350,Car_Name_Royal Enfield Classic 350,Car_Name_Royal Enfield Classic 500,Car_Name_Royal Enfield Thunder 350,Car_Name_Royal Enfield Thunder 500,Car_Name_Suzuki Access 125,Car_Name_TVS Apache RTR 160,Car_Name_TVS Apache RTR 180,Car_Name_TVS Jupyter,Car_Name_TVS Sport,Car_Name_TVS Wego,Car_Name_UM Renegade Mojave,Car_Name_Yamaha FZ v 2.0,Car_Name_Yamaha FZ 16,Car_Name_Yamaha FZ S,Car_Name_Yamaha FZ S V 2.0,Car_Name_Yamaha Fazer,Car_Name_alto 800,Car_Name_alto k10,Car_Name_amaze,Car_Name_baleno,Car_Name_brio,Car_Name_camry,Car_Name_ciaz,Car_Name_city,Car_Name_corolla,Car_Name_corolla altis,Car_Name_creta,Car_Name_dzire,Car_Name_elantra,Car_Name_eon,Car_Name_ertiga,Car_Name_etios cross,Car_Name_etios g,Car_Name_etios gd,Car_Name_etios liva,Car_Name_fortuner,Car_Name_grand i10,Car_Name_i10,Car_Name_i20,Car_Name_ignis,Car_Name_innova,Car_Name_jazz,Car_Name_land cruiser,Car_Name_omni,Car_Name_ritz,Car_Name_s cross,Car_Name_swift,Car_Name_sx4,Car_Name_verna,Car_Name_vitara brezza,Car_Name_wagon r,Car_Name_xcent,Seller_Type_Individual
0,3.35,27000,Petrol,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,4.75,43000,Diesel,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
2,7.25,6900,Petrol,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2.85,5200,Petrol,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
4,4.60,42450,Diesel,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
5,9.25,2071,Diesel,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
6,6.75,18796,Petrol,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,6.50,33429,Diesel,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,

One hot encoding using One hot encoder of sklearn

In [97]:
print(df.head())

  Car_Name  Selling_Price  Kms_Driven Fuel_Type Seller_Type Transmission
0     ritz           3.35       27000    Petrol      Dealer       Manual
1      sx4           4.75       43000    Diesel      Dealer       Manual
2     ciaz           7.25        6900    Petrol      Dealer       Manual
3  wagon r           2.85        5200    Petrol      Dealer       Manual
4    swift           4.60       42450    Diesel      Dealer       Manual


In [98]:
df['Transmission'] = df['Transmission'].map({
    'Manual' : 0 ,
    'Automatic' : 1
})
print(df.head())
print(df.tail())

  Car_Name  Selling_Price  Kms_Driven Fuel_Type Seller_Type  Transmission
0     ritz           3.35       27000    Petrol      Dealer             0
1      sx4           4.75       43000    Diesel      Dealer             0
2     ciaz           7.25        6900    Petrol      Dealer             0
3  wagon r           2.85        5200    Petrol      Dealer             0
4    swift           4.60       42450    Diesel      Dealer             0
    Car_Name  Selling_Price  Kms_Driven Fuel_Type Seller_Type  Transmission
296     city           9.50       33988    Diesel      Dealer             0
297     brio           4.00       60000    Petrol      Dealer             0
298     city           3.35       87934    Petrol      Dealer             0
299     city          11.50        9000    Diesel      Dealer             0
300     brio           5.30        5464    Petrol      Dealer             0


In [99]:
pd.set_option('display.max_rows', None)
print(df['Transmission'])

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     1
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     1
41     0
42     0
43     0
44     0
45     1
46     0
47     0
48     0
49     1
50     1
51     1
52     1
53     1
54     0
55     1
56     0
57     0
58     0
59     1
60     0
61     0
62     1
63     1
64     1
65     0
66     1
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     1
78     1
79     1
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     1
94     1
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
1

In [100]:
df['Transmission'].value_counts()

Transmission
0    261
1     40
Name: count, dtype: int64

In [101]:
print(df.head())

  Car_Name  Selling_Price  Kms_Driven Fuel_Type Seller_Type  Transmission
0     ritz           3.35       27000    Petrol      Dealer             0
1      sx4           4.75       43000    Diesel      Dealer             0
2     ciaz           7.25        6900    Petrol      Dealer             0
3  wagon r           2.85        5200    Petrol      Dealer             0
4    swift           4.60       42450    Diesel      Dealer             0


In [102]:
df['Fuel_Type'].value_counts()

Fuel_Type
Petrol    239
Diesel     60
CNG         2
Name: count, dtype: int64

In [103]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
x = df.iloc[ : , 0 : 5]
y = df['Transmission']

In [104]:
x_train , x_test , y_train , y_test = train_test_split(x , y)

In [105]:
print(x)

                      Car_Name  Selling_Price  Kms_Driven Fuel_Type  \
0                         ritz           3.35       27000    Petrol   
1                          sx4           4.75       43000    Diesel   
2                         ciaz           7.25        6900    Petrol   
3                      wagon r           2.85        5200    Petrol   
4                        swift           4.60       42450    Diesel   
5                vitara brezza           9.25        2071    Diesel   
6                         ciaz           6.75       18796    Petrol   
7                      s cross           6.50       33429    Diesel   
8                         ciaz           8.75       20273    Diesel   
9                         ciaz           7.45       42367    Diesel   
10                    alto 800           2.85        2135    Petrol   
11                        ciaz           6.85       51000    Diesel   
12                        ciaz           7.50       15000    Petrol   
13    

In [106]:
print(y)

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     1
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     1
41     0
42     0
43     0
44     0
45     1
46     0
47     0
48     0
49     1
50     1
51     1
52     1
53     1
54     0
55     1
56     0
57     0
58     0
59     1
60     0
61     0
62     1
63     1
64     1
65     0
66     1
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     1
78     1
79     1
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     1
94     1
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
1

In [107]:
oe = OneHotEncoder(drop = 'first' , sparse_output = False , dtype = int)
#oe.fit(x_train , y_train)
x_train_new = oe.fit_transform(x_train[['Fuel_Type' , 'Seller_Type']])
x_test_new = oe.transform(x_test[['Fuel_Type' , 'Seller_Type']])

In [108]:
print('x_train_shape :- ' , x_train.shape)
print('x_train_new_shape :- ' , x_train_new.shape)

x_train_shape :-  (225, 5)
x_train_new_shape :-  (225, 3)


In [109]:
print(x_train)

                      Car_Name  Selling_Price  Kms_Driven Fuel_Type  \
260                       city           9.15       29223    Petrol   
111  Royal Enfield Thunder 350           1.15        8700    Petrol   
29                        ciaz           7.45       45000    Diesel   
171           Hero Passion Pro           0.40        6700    Petrol   
278                       jazz           6.00        4000    Petrol   
180     Hero Honda Passion Pro           0.30       60000    Petrol   
300                       brio           5.30        5464    Petrol   
272                       city           7.50       27600    Petrol   
254                       city           5.25       54242    Petrol   
104  Royal Enfield Classic 350           1.35        4100    Petrol   
220                        eon           3.50       38488    Petrol   
135           Bajaj Pulsar 150           0.65        5000    Petrol   
266                      amaze           3.65       35000    Petrol   
21    

In [110]:
print(x_train_new)

[[0 1 0]
 [0 1 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 

In [115]:
np.hstack((x_train[['Car_Name' , 'Selling_Price' , 'Kms_Driven']].values,x_train_new))

array([['city', 9.15, 29223, 0, 1, 0],
       ['Royal Enfield Thunder 350', 1.15, 8700, 0, 1, 1],
       ['ciaz', 7.45, 45000, 1, 0, 0],
       ...,
       ['dzire', 4.65, 48767, 0, 1, 0],
       ['jazz', 7.4, 15059, 0, 1, 0],
       ['verna', 5.35, 32322, 1, 0, 0]], shape=(225, 6), dtype=object)

In [116]:
np.hstack((x_train[['Car_Name' , 'Selling_Price' , 'Kms_Driven']].values,x_train_new)).shape

(225, 6)

one hot encoding on top categories(car name)

In [118]:
df['Car_Name'].value_counts()

Car_Name
city                         26
corolla altis                16
verna                        14
fortuner                     11
brio                         10
ciaz                          9
innova                        9
i20                           9
grand i10                     8
Royal Enfield Classic 350     7
amaze                         7
jazz                          7
sx4                           6
ertiga                        6
eon                           6
swift                         5
alto k10                      5
i10                           5
ritz                          4
wagon r                       4
dzire                         4
etios liva                    4
Royal Enfield Thunder 350     4
Bajaj Pulsar 150              4
etios cross                   3
etios g                       3
Royal Enfield Thunder 500     3
Bajaj Avenger 220             3
Honda CB Hornet 160R          3
Yamaha FZ S V 2.0             3
TVS Apache RTR 160            3

In [119]:
counts = df['Car_Name'].value_counts()
threshold = 10 

In [122]:
counts[counts < threshold].index

Index(['ciaz', 'innova', 'i20', 'grand i10', 'Royal Enfield Classic 350',
       'amaze', 'jazz', 'sx4', 'ertiga', 'eon', 'swift', 'alto k10', 'i10',
       'ritz', 'wagon r', 'dzire', 'etios liva', 'Royal Enfield Thunder 350',
       'Bajaj Pulsar 150', 'etios cross', 'etios g',
       'Royal Enfield Thunder 500', 'Bajaj Avenger 220',
       'Honda CB Hornet 160R', 'Yamaha FZ S V 2.0', 'TVS Apache RTR 160',
       'Bajaj Pulsar NS 200', 'xcent', 'creta', 'KTM RC200',
       'Royal Enfield Classic 500', 'Honda CBR 150', 'Hero Extreme',
       'Bajaj Avenger 220 dtsi', 'Yamaha FZ  v 2.0', 'Bajaj Pulsar 220 F',
       'TVS Apache RTR 180', 'Honda Activa 4G', 'Hero Splender iSmart',
       'Activa 3g', 'Hero Passion Pro', 'Honda Karizma', 'Honda CB Shine',
       'Honda CB twister', 'Bajaj Discover 125', 'elantra', 'vitara brezza',
       's cross', 'alto 800', 'ignis', '800', 'baleno', 'omni', 'corolla',
       'etios gd', 'camry', 'land cruiser', 'UM Renegade Mojave',
       'Bajaj Domi

In [128]:
repl = counts[counts < threshold].index
pd.get_dummies(df['Car_Name'].replace(repl , 'uncommon') , dtype = int)

,brio,city,corolla altis,fortuner,uncommon,verna
0,0,0,0,0,1,0
1,0,0,0,0,1,0
2,0,0,0,0,1,0
3,0,0,0,0,1,0
4,0,0,0,0,1,0
5,0,0,0,0,1,0
6,0,0,0,0,1,0
7,0,0,0,0,1,0
8,0,0,0,0,1,0
9,0,0,0,0,1,0
